# Generated by Django 3.2.7 on 2021-11-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tomeet_date_of_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='date_of_meeting',
            field=models.DateField(),
        ),
    ]
