# Generated by Django 3.2.7 on 2021-11-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211110_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('done_for_today', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('comment', models.TextField()),
            ],
        ),
    ]
